### ISSUE TITLE
Shows MIT license as apache v2

### ISSUE THREAD

**Issue by codesForLiving** [yshrsmz/LicenseAdapter#19]
`dataset.add(Licenses.fromGitHub("afollestad/material-dialogs"));`

The item in recyclerview will show "apache license v2.0", although the license is MIT. It happens for all MIT licenses.

**Comment by yshrsmz** [comment]
checkout following code, there is a overload method which can specify license

https://github.com/yshrsmz/LicenseAdapter/blob/master/library/src/main/java/net/yslibrary/licenseadapter/Licenses.java#L64

or you can manually create `GitHubLicenseEntry`

**Comment by yshrsmz** [comment]
or this method.
https://github.com/yshrsmz/LicenseAdapter/blob/master/library/src/main/java/net/yslibrary/licenseadapter/Licenses.java#L68

maybe we need dedicated method for each licenses, such as `Licenses#fromGitHubMIT`, Licenses#fromGitHubApacheV2`

**Comment by codesForLiving** [comment]
@yshrsmz so how is it currently filling up the field as "apache license v2.0" ? Does it work for GPL v3?[without the overload that you mention]

**Comment by codesForLiving** [comment]
@yshrsmz  yes overload would work, but that would be cumbersome. I think since the license text is included it is not violation of MIT license terms. Please correct if I am wrong.

**Comment by yshrsmz** [comment]
> how is it currently filling up the field as "apache license v2.0"

https://github.com/yshrsmz/LicenseAdapter/blob/master/library/src/main/java/net/yslibrary/licenseadapter/Licenses.java#L37

```java
  public static GitHubLicenseEntry fromGitHub(String gitRepo) {
    return new GitHubLicenseEntry(DEF_LICENSE_NAME, gitRepo, DEF_BRANCH, null, FILE_TXT);
  }
```

You are using this method, and `DEF_LICENSE_NAME` is Apache v2, so that's why(Am I understand you correctly?)

> Does it work for GPL v3?

Yes, there are 3 ways

1. If it's hosted on GitHub and provide `LICENSE` file, you can write like this

```java
new GitHubLicenseEntry("GPL v3", "some/gitrepo", master, null, Licenses.FILE_TXT);
// Licenses.FILE_TXT could be any string that represents repo's license file name
```

2. If it's hosted on GitHub and does not provide `LICENSE`(or any other variant) file, you need to create your own [`License`](https://github.com/yshrsmz/LicenseAdapter/blob/master/library/src/main/java/net/yslibrary/licenseadapter/License.java) instance. See [here](https://github.com/yshrsmz/LicenseAdapter/blob/master/library/src/main/java/net/yslibrary/licenseadapter/Licenses.java#L27) for how to.

3. If it's not hosted on GitHub, you need to create your own `LicenseEntry` which is extended from [`BaseLicenseEntry`](https://github.com/yshrsmz/LicenseAdapter/blob/master/library/src/main/java/net/yslibrary/licenseadapter/internal/BaseLicenseEntry.java) or implements [`LicenseEntry`](https://github.com/yshrsmz/LicenseAdapter/blob/master/library/src/main/java/net/yslibrary/licenseadapter/LicenseEntry.java)


> I think since the license text is included it is not violation of MIT license terms

Sorry I couldn't understand what you mean. Could you elaborate on this?
FYI this library does not include any actual license text, just fetch those from target repository.

**Comment by codesForLiving** [comment]
> so I chose it as a default license.

the method name should reflect that, may be fromGitHubApachev2, like you said earlier.

> Sorry I couldn't understand what you mean. Could you elaborate on this?

with my original usage, since MIT license was shown as apache v2, but the license text was also included, it should be okay, as per the MIT license terms, since it requires the license to be included, which was being done.

**Comment by yshrsmz** [comment]
yes, thanks for the suggestion, will add those methods in future release

for now, you can write like this:

`dataset.add(Licenses.fromGitHub("afollestad/material-dialogs", Licenses.NAME_MIT, Licenses.FILE_TXT));`

**Comment by yshrsmz** [comment]
I made a PR to address this issue. Please take a look and leave some comments if you have any suggestion :)
https://github.com/yshrsmz/LicenseAdapter/pull/21
